const $=s=>document.querySelector(s), app=$('#app'), content=$('#content'), nav=$('#navigation');
const state={data:null,mode:'business',tab:'shop',cart:{},admin:null};
const money=n=>new Intl.NumberFormat('nl-NL',{style:'currency',currency:'USD',minimumFractionDigits:2}).format(Number(n||0));
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const post=async(name,data={})=>{try{return await (await fetch(`https://${GetParentResourceName()}/${name}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)})).json()}catch{return{success:false}}};
function toast(message,ok=true){const e=document.createElement('div');e.className=`toast ${ok?'ok':'error'}`;e.textContent=message;$('#toastRoot').append(e);setTimeout(()=>e.remove(),2600)}
function setTitle(title,eye='BEDRIJFSBEHEER'){$('#title').textContent=title;$('#eyebrow').textContent=eye}
function tabs(){
 if(state.mode==='admin')return[{id:'creator',i:'＋',t:'Nieuwe locatie'},{id:'locations',i:'⌖',t:'Locaties'},{id:'workroutes',i:'↝',t:'NPC-werkroutes'}];
 const m=state.data?.management, type=state.data?.business?.type;
 const list=[];if(type!=='fuel')list.push({id:'shop',i:'▦',t:'Winkel'});if(type!=='shop')list.push({id:'fuel',i:'⛽',t:'Tanken'});
 if(m){const p=m.permissions||{},all=m.isOwner||p.all,hasShop=type!=='fuel',hasFuel=type!=='shop';list.push({id:'dashboard',i:'◫',t:'Overzicht'});if(hasShop&&(all||p.products))list.push({id:'stock',i:'◩',t:'Winkelvoorraad'});if(hasShop&&(all||p.orders))list.push({id:'orders',i:'⇄',t:'Productbestellingen'});if(hasFuel&&(all||p.orders||p.settings))list.push({id:'fuel_management',i:'▰',t:'Brandstofbeheer'});if(all||p.employees)list.push({id:'employees',i:'♙',t:'Personeel'});if(all||p.finance)list.push({id:'finance',i:'$',t:'Financiën'});if(all||p.settings)list.push({id:'upgrades',i:'◆',t:'Upgrades'},{id:'settings',i:'⚙',t:'Instellingen'})}
 return list;
}
function chrome(){
 const b=state.mode==='admin'?null:state.data.business;
 $('#businessIdentity').innerHTML=state.mode==='admin'?'<small>Administratie</small><strong>Locatiecreator</strong><span>Serverbeheer</span>':`<small>${esc(b.type)}</small><strong>${esc(b.name)}</strong><span>${b.owner_identifier?'Spelerbedrijf':'Te koop'}</span>`;
 nav.innerHTML=tabs().map(x=>`<button data-tab="${x.id}" class="${state.tab===x.id?'active':''}"><i>${x.i}</i>${x.t}</button>`).join('');
 $('#balancePill').innerHTML=state.mode==='admin'?'':state.data.management?`<div class="balance-pill">Bedrijfsrekening <b>${money(b.balance)}</b></div>`:`<div class="balance-pill">Jouw bank <b>${money(state.data.playerMoney)}</b></div>`;
 nav.querySelectorAll('button').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;render()});
}
function render(){chrome();const fn=views[state.mode==='admin'?`admin_${state.tab}`:state.tab]||views.shop;content.innerHTML=fn();setTitle(content.firstElementChild?.dataset.title||'Overzicht',state.mode==='admin'?'RS ADMINISTRATIE':'RS BUSINESS SUITE');bind()}
const stat=(label,value,note='')=>`<div class="stat"><small>${label}</small><strong>${value}</strong>${note?`<em>${note}</em>`:''}</div>`;
const productCard=p=>`<article class="product"><span class="category">${esc(p.category)}</span><h3>${esc(p.label)}</h3><div class="price">${money(p.price)}</div><div class="stock">${p.stock} op voorraad</div><div class="product-actions"><input id="qty-${p.item}" type="number" min="1" max="100" value="1"><button class="btn add-cart" data-item="${p.item}" ${p.stock<1?'disabled':''}>Toevoegen</button></div></article>`;
const purchaseView=b=>`<div data-title="Bedrijf kopen" class="hero"><div><span class="badge orange">TE KOOP</span><h2>${esc(b.name)} staat te koop</h2><p>Koop deze locatie en krijg direct toegang tot het volledige bedrijfsbeheer, de financiën, het personeel, de voorraad en de instellingen.</p></div><div class="purchase-action"><small>Eenmalige koopprijs</small><strong>${money(b.purchase_price)}</strong><button class="btn" data-act="buy">Bedrijf kopen</button></div></div>`;
const views={
 shop(){const d=state.data,b=d.business;if(!b.owner_identifier)return purchaseView(b);const products=d.products.filter(p=>p.stock>0);return `<div data-title="Winkel" class="grid-2"><div class="card"><div class="card-head"><h2>Assortiment</h2><span>${products.length} producten beschikbaar</span></div><div class="product-grid">${products.map(productCard).join('')||'<div class="empty">De schappen zijn leeg.</div>'}</div></div><aside class="card"><div class="card-head"><h2>Winkelmand</h2><span id="cartCount">0 items</span></div><div id="cart"></div></aside></div>`},
 fuel(){const b=state.data.business;if(!b.owner_identifier)return purchaseView(b);const capacity=Number(b.fuel_capacity)||0,pct=capacity>0?Math.round(Number(b.fuel_stock||0)/capacity*100):0;return `<div data-title="Tankstation"><div class="hero"><div><h2>${esc(b.name)}</h2><p>Gebruik buiten de pomp via ox_target om je voertuig te tanken. Betaling gaat veilig via de bank.</p></div><div><small>Prijs per liter</small><h2>${money(b.fuel_sell_price)}</h2></div></div><div class="grid-3">${stat('Beschikbaar',`${Number(b.fuel_stock).toFixed(0)} L`)}${stat('Capaciteit',`${capacity.toFixed(0)} L`)}${stat('Voorraadniveau',`${pct}%`)} </div></div>`},
 dashboard(){const d=state.data,b=d.business,m=d.management,hasShop=b.type!=='fuel',hasFuel=b.type!=='shop',productStock=d.products.reduce((a,p)=>a+p.stock,0),stockStat=hasShop?stat('Winkelvoorraad',productStock,hasFuel?`${Number(b.fuel_stock).toFixed(0)} L brandstof`:'Producteenheden'):stat('Brandstofvoorraad',`${Number(b.fuel_stock).toFixed(0)} L`,`${Math.round(Number(b.fuel_stock)/Number(b.fuel_capacity)*100)||0}% gevuld`);return `<div data-title="Overzicht"><div class="stats">${stat('Saldo',money(b.balance),'Bedrijfsrekening')}${stat('Inkomsten 7 dagen',money(m.stats.income),'Bruto geregistreerd')}${stat('Uitgaven 7 dagen',money(m.stats.expenses))}${stockStat}</div><div class="grid-2"><section class="card"><div class="card-head"><h2>Recente transacties</h2></div>${transactionTable(m.transactions.slice(0,8))}</section><section class="card"><div class="card-head"><h2>Bedrijfsstatus</h2></div><div class="cart-line"><span>${hasFuel&&!hasShop?'Tankstationstatus':'Winkelstatus'}</span><span class="badge ${b.is_open?'green':'orange'}">${b.is_open?'Geopend':'Gesloten'}</span></div><div class="cart-line"><span>Spelermedewerkers</span><b>${m.employees.length}</b></div><div class="cart-line"><span>NPC-medewerkers</span><b>${m.npcs.length}</b></div>${hasShop?`<div class="cart-line"><span>Open productorders</span><b>${m.orders.filter(o=>!['received','cancelled'].includes(o.status)).length}</b></div>`:`<div class="cart-line"><span>Verkoopprijs</span><b>${money(b.fuel_sell_price)} / L</b></div>`}</section></div></div>`},
 fuel_management(){const d=state.data,b=d.business,m=d.management,p=m.permissions||{},all=m.isOwner||p.all,canOrder=all||p.orders,canSettings=all||p.settings,stock=Number(b.fuel_stock)||0,capacity=Number(b.fuel_capacity)||0,available=Math.max(0,capacity-stock),pct=capacity>0?Math.round(stock/capacity*100):0,fuelTransactions=m.transactions.filter(t=>['fuel_sale','fuel_order'].includes(t.type));return `<div data-title="Brandstofbeheer"><div class="stats">${stat('Tankvoorraad',`${stock.toFixed(0)} L`)}${stat('Tankcapaciteit',`${capacity.toFixed(0)} L`)}${stat('Vulniveau',`${pct}%`)}${stat('Verkoopprijs',`${money(b.fuel_sell_price)} / L`)}</div><div class="grid-2"><section class="card"><div class="card-head"><h2>Brandstof inkopen</h2><span>Inkoopprijs ${money(b.fuel_buy_price)} per liter</span></div>${canOrder?`<div class="form-grid"><label class="wide">Aantal liter<input id="fuelOrder" type="number" min="1" max="${available}" placeholder="Maximaal ${available.toFixed(0)} liter"></label><div class="wide actions"><button class="btn secondary fuel-quick" data-litres="1000">1.000 L</button><button class="btn secondary fuel-quick" data-litres="2500">2.500 L</button><button class="btn secondary fuel-quick" data-litres="${available}">Tank vullen</button></div><div class="wide cart-line"><span>Geschatte kosten</span><b id="fuelOrderTotal">${money(0)}</b></div><div class="wide"><button class="btn" data-act="fuelOrder">Brandstof bestellen</button></div></div>`:'<div class="empty">Je hebt geen toestemming om brandstof te bestellen.</div>'}</section><section class="card"><div class="card-head"><h2>Literprijs beheren</h2><span>Minimaal de inkoopprijs</span></div>${canSettings?`<div class="form-grid"><label class="wide">Verkoopprijs per liter<input id="fuelSalePrice" type="number" step="0.01" min="${b.fuel_buy_price}" max="10" value="${b.fuel_sell_price}"></label><div class="wide"><button class="btn" data-act="saveFuelPrice">Prijs opslaan</button></div></div>`:'<div class="empty">Je hebt geen toestemming om de literprijs te wijzigen.</div>'}</section></div><section class="card" style="margin-top:17px"><div class="card-head"><h2>Brandstoftransacties</h2><span>Verkoop en inkoop</span></div>${transactionTable(fuelTransactions)}</section></div>`},
 stock(){return `<div data-title="Voorraad"><section class="card"><div class="card-head"><h2>Productbeheer</h2><span>Prijswijzigingen worden direct actief</span></div><div class="table"><div class="row head"><span>Product</span><span>Inkoop</span><span>Verkoop</span><span>Voorraad</span><span></span></div>${state.data.products.map(p=>`<div class="row"><b>${esc(p.label)}</b><span>${money(p.purchasePrice)}</span><input id="price-${p.item}" type="number" min="${p.purchasePrice}" max="${p.maxPrice}" value="${p.price}"><span>${p.stock}</span><button class="btn secondary save-price" data-item="${p.item}">Opslaan</button></div>`).join('')}</div></section></div>`},
 orders(){const m=state.data.management;return `<div data-title="Bestellingen"><div class="grid-2"><section class="card"><div class="card-head"><h2>Nieuwe voorraadorder</h2><span>Levering of zelf afhalen</span></div><div class="table">${state.data.products.map(p=>`<div class="cart-line"><span>${esc(p.label)} <small>${money(p.purchasePrice)}</small></span><input style="width:80px" class="order-qty" data-item="${p.item}" type="number" min="0" max="1000" value="0"></div>`).join('')}</div><div class="actions" style="margin-top:16px"><button class="btn order" data-mode="delivery">Laten bezorgen</button><button class="btn secondary order" data-mode="pickup">Zelf afhalen</button></div></section><section class="card"><div class="card-head"><h2>Orderhistorie</h2></div>${m.orders.map(o=>`<div class="cart-line"><div><b>#${o.id}</b><small style="display:block;color:var(--muted)">${esc(o.status)} · ${esc(o.delivery_mode)}</small></div><div><b>${money(o.total)}</b>${['ready','ready_pickup'].includes(o.status)?`<button class="btn green receive" data-id="${o.id}" style="margin-left:8px">Ontvangen</button>`:''}</div></div>`).join('')||'<div class="empty">Nog geen bestellingen.</div>'}</section></div></div>`},
 employees(){const m=state.data.management,roles=Object.entries(state.data.config.npcRoles);return `<div data-title="Personeel"><div class="grid-2"><section class="card"><div class="card-head"><h2>Spelermedewerkers</h2><button class="btn" data-modal="player">Aannemen</button></div>${m.employees.map(e=>`<div class="cart-line"><div><b>${esc(e.name)}</b><small style="display:block;color:var(--muted)">${esc(e.role)}</small></div><button class="btn danger remove-employee" data-id="${esc(e.identifier)}">Ontslaan</button></div>`).join('')||'<div class="empty">Geen medewerkers.</div>'}</section><section class="card"><div class="card-head"><h2>NPC-medewerkers</h2><button class="btn" data-modal="npc">NPC aannemen</button></div>${m.npcs.map(n=>`<div class="cart-line"><div><b>${esc(n.name)}</b><small style="display:block;color:var(--muted)">${esc(n.role)} · ${money(n.wage)} loon</small></div><button class="btn danger remove-npc" data-id="${n.id}">Ontslaan</button></div>`).join('')||'<div class="empty">Geen NPC-medewerkers.</div>'}</section></div></div>`},
 finance(){const m=state.data.management,b=state.data.business;return `<div data-title="Financiën"><div class="stats">${stat('Bedrijfssaldo',money(b.balance))}${stat('7d inkomsten',money(m.stats.income))}${stat('7d uitgaven',money(m.stats.expenses))}${stat('Resultaat',money(m.stats.income-m.stats.expenses))}</div><div class="grid-2"><section class="card"><div class="card-head"><h2>Bankieren</h2></div><label>Bedrag<input id="bankAmount" type="number" min="1" placeholder="0.00"></label><div class="actions" style="margin-top:13px"><button class="btn bank" data-mode="deposit">Storten</button><button class="btn secondary bank" data-mode="withdraw">Opnemen</button></div></section><section class="card"><div class="card-head"><h2>Transacties</h2></div>${transactionTable(m.transactions)}</section></div></div>`},
 upgrades(){const b=state.data.business,entries=Object.entries(state.data.config.upgrades).filter(([k])=>b.type==='combined'||(b.type==='fuel'?!['storage_1','storage_2','express'].includes(k):k!=='fuel_1'));return `<div data-title="Upgrades"><div class="grid-3">${entries.map(([k,u])=>`<article class="card"><span class="badge">UITBREIDING</span><h2 style="margin:14px 0 8px">${esc(u.label)}</h2><p style="color:var(--muted);font-size:11px;min-height:32px">${esc(u.description)}</p><b>${money(u.price)}</b><button class="btn upgrade" data-key="${k}" style="width:100%;margin-top:16px" ${b.upgrades?.[k]?'disabled':''}>${b.upgrades?.[k]?'Actief':'Aanschaffen'}</button></article>`).join('')}</div></div>`},
 settings(){const b=state.data.business;return `<div data-title="Instellingen"><section class="card" style="max-width:650px"><div class="card-head"><h2>Bedrijfsinstellingen</h2></div><div class="form-grid"><label class="wide">Bedrijfsnaam<input id="setName" value="${esc(b.name)}" maxlength="48"></label><label class="switch wide"><input id="setOpen" type="checkbox" ${b.is_open?'checked':''}> ${b.type==='fuel'?'Tankstation':'Bedrijf'} geopend</label><div class="wide"><button class="btn" data-act="saveSettings">Instellingen opslaan</button></div></div></section></div>`},
 admin_creator(){const a=state.admin;return `<div data-title="Nieuwe locatie"><section class="card" style="max-width:760px"><div class="card-head"><h2>Bedrijfslocatie aanmaken</h2><span>Je huidige positie wordt gebruikt</span></div><div class="form-grid"><label>Bedrijfsnaam<input id="aName" placeholder="Bijv. RS Supermarkt"></label><label>Type<select id="aType">${Object.entries(a.types).map(([k,v])=>`<option value="${k}">${esc(v.label)}</option>`).join('')}</select></label><label>Koopprijs<input id="aPrice" type="number" value="${a.defaults.purchasePrice}"></label><label>NPC-model<input id="aModel" value="${a.defaults.npcModel}"></label><label class="wide">Locatie<div style="display:flex;gap:8px"><input id="aCoords" readonly placeholder="Klik op huidige positie"><button class="btn secondary" data-act="position">Huidige positie</button></div></label><div class="wide"><button class="btn" data-act="adminCreate">Locatie aanmaken</button></div></div></section></div>`},
 admin_locations(){return `<div data-title="Locaties"><section class="card"><div class="card-head"><h2>Alle bedrijfslocaties</h2><span>${state.admin.businesses.length} locaties</span></div><div class="table">${state.admin.businesses.map(b=>`<div class="row"><b>${esc(b.name)}</b><span class="badge">${esc(b.type)}</span><span>${money(b.purchasePrice)}</span><span>${b.owner?'Verkocht':'Te koop'}</span><button class="btn danger admin-delete" data-id="${b.id}">Verwijderen</button></div>`).join('')}</div></section></div>`},
 admin_workroutes(){const a=state.admin,roles=Object.keys(a.npcRoles),selected=state.admin.workRole||'cashier',scenarios=a.npcScenarios[selected]||[];return `<div data-title="NPC-werkroutes"><div class="grid-2"><section class="card"><div class="card-head"><h2>Werkpunt plaatsen</h2><span>Volgorde wordt automatisch bepaald</span></div><div class="form-grid"><label>Bedrijf<select id="wpBusiness">${a.businesses.map(b=>`<option value="${b.id}">${esc(b.name)}</option>`).join('')}</select></label><label>NPC-rol<select id="wpRole">${roles.map(r=>`<option value="${r}" ${r===selected?'selected':''}>${esc(a.npcRoles[r].label)}</option>`).join('')}</select></label><label class="wide">Omschrijving<input id="wpLabel" placeholder="Bijv. Frisdrank bijvullen"></label><label>Werkanimatie<select id="wpScenario">${scenarios.map(s=>`<option value="${s}">${esc(s.replaceAll('_',' '))}</option>`).join('')}</select></label><label>Duur op dit punt (seconden)<input id="wpDuration" type="number" min="3" max="60" value="9"></label><label class="wide">Positie en kijkrichting<div style="display:flex;gap:8px"><input id="wpCoords" readonly placeholder="Ga op de werkplek staan"><button class="btn secondary" data-act="workPosition">Huidige positie</button></div></label><div class="wide"><button class="btn" data-act="addWorkpoint">Werkpunt toevoegen</button></div></div></section><section class="card"><div class="card-head"><h2>Ingestelde werkpunten</h2><span>${a.workpoints.length} punten</span></div>${a.workpoints.map(p=>`<div class="cart-line"><div><b>${esc(p.business_name)} · ${esc(p.label)}</b><small style="display:block;color:var(--muted)">${esc(a.npcRoles[p.role]?.label||p.role)} · route #${p.sequence} · ${Math.round(p.duration_ms/1000)} sec.</small></div><button class="btn danger delete-workpoint" data-id="${p.id}">Verwijderen</button></div>`).join('')||'<div class="empty">Nog geen werkpunten. Niet-kassiers gebruiken tijdelijk een kleine vrije werkzone.</div>'}</section></div></div>`}
};
function transactionTable(rows){return rows?.map(t=>`<div class="cart-line"><div><b>${esc(t.description)}</b><small style="display:block;color:var(--muted)">${esc(t.created_at)}</small></div><b style="color:${Number(t.amount)>=0?'var(--green)':'var(--red)'}">${Number(t.amount)>=0?'+':''}${money(t.amount)}</b></div>`).join('')||'<div class="empty">Geen transacties.</div>'}
async function call(name,args=[]){const r=await post(name,{args});if(r.message)toast(r.message,r.success);return r}
function renderCart(){const e=$('#cart');if(!e)return;const ps=state.data.products,total=Object.entries(state.cart).reduce((a,[i,q])=>a+(ps.find(p=>p.item===i)?.price||0)*q,0),count=Object.values(state.cart).reduce((a,b)=>a+b,0);e.innerHTML=Object.entries(state.cart).map(([i,q])=>{const p=ps.find(x=>x.item===i);return `<div class="cart-line"><span>${q}× ${esc(p.label)}</span><b>${money(q*p.price)}</b></div>`}).join('')||'<div class="empty">Je winkelmand is leeg.</div>';if(count)e.innerHTML+=`<div class="cart-total"><span>Totaal</span><span>${money(total)}</span></div><div class="actions"><button class="btn checkout" data-pay="bank">Betalen met bank</button><button class="btn secondary checkout" data-pay="cash">Contant</button></div>`;$('#cartCount')&&($('#cartCount').textContent=`${count} items`);bindDynamic()}
function modal(type){const roles=state.data.config.npcRoles;$('#modalRoot').innerHTML=`<div class="modal-backdrop"><div class="modal"><h2>${type==='player'?'Spelermedewerker aannemen':'NPC-medewerker aannemen'}</h2><div class="form-grid">${type==='player'?'<label>Server ID<input id="mTarget" type="number"></label><label>Functie<select id="mRole"><option value="cashier">Kassamedewerker</option><option value="employee">Medewerker</option><option value="manager">Manager</option></select></label>':`<label>Naam<input id="mName" placeholder="Naam medewerker"></label><label>Rol<select id="mRole">${Object.entries(roles).map(([k,v])=>`<option value="${k}">${esc(v.label)} · ${money(v.purchasePrice)}</option>`).join('')}</select></label>`}<div class="wide actions"><button class="btn" id="modalSave">Aannemen</button><button class="btn secondary" id="modalCancel">Annuleren</button></div></div></div></div>`;$('#modalCancel').onclick=()=>$('#modalRoot').innerHTML='';$('#modalSave').onclick=async()=>{let r;if(type==='player')r=await call('addEmployee',[Number($('#mTarget').value),$('#mRole').value]);else{const pos=await post('getPosition');r=await call('hireNpc',[$('#mRole').value,$('#mName').value,pos])}if(r.success)$('#modalRoot').innerHTML=''};}
function bindDynamic(){document.querySelectorAll('.checkout').forEach(e=>e.onclick=async()=>{const cart=Object.entries(state.cart).map(([item,quantity])=>({item,quantity}));const r=await call('checkout',[cart,e.dataset.pay]);if(r.success){state.cart={};renderCart()}})}
function bind(){
 document.querySelectorAll('[data-action="close"]').forEach(e=>e.onclick=()=>post('close'));
 document.querySelectorAll('.add-cart').forEach(e=>e.onclick=()=>{const p=state.data.products.find(x=>x.item===e.dataset.item),q=Number($(`#qty-${e.dataset.item}`).value||1);state.cart[p.item]=Math.min(p.stock,(state.cart[p.item]||0)+q);renderCart()});
 renderCart();
 $('[data-act="buy"]')?.addEventListener('click',()=>call('purchaseBusiness'));
 document.querySelectorAll('.save-price').forEach(e=>e.onclick=()=>call('updateProduct',[e.dataset.item,Number($(`#price-${e.dataset.item}`).value)]));
 document.querySelectorAll('.order').forEach(e=>e.onclick=()=>call('createOrder',[Array.from(document.querySelectorAll('.order-qty')).map(x=>({item:x.dataset.item,quantity:Number(x.value)})).filter(x=>x.quantity>0),e.dataset.mode]));
 document.querySelectorAll('.receive').forEach(e=>e.onclick=()=>call('receiveOrder',[Number(e.dataset.id)]));
 document.querySelectorAll('.bank').forEach(e=>e.onclick=()=>call('bank',[e.dataset.mode,Number($('#bankAmount').value)]));
 document.querySelectorAll('.upgrade').forEach(e=>e.onclick=()=>call('upgrade',[e.dataset.key]));
 document.querySelectorAll('.remove-employee').forEach(e=>e.onclick=()=>call('removeEmployee',[e.dataset.id]));document.querySelectorAll('.remove-npc').forEach(e=>e.onclick=()=>call('removeNpc',[Number(e.dataset.id)]));
 document.querySelectorAll('[data-modal]').forEach(e=>e.onclick=()=>modal(e.dataset.modal));
 $('[data-act="saveSettings"]')?.addEventListener('click',()=>call('settings',[{name:$('#setName').value,isOpen:$('#setOpen').checked}]));
 $('[data-act="saveFuelPrice"]')?.addEventListener('click',()=>call('settings',[{name:state.data.business.name,isOpen:state.data.business.is_open,fuelPrice:Number($('#fuelSalePrice').value)}]));
 $('[data-act="fuelOrder"]')?.addEventListener('click',()=>call('orderFuel',[Number($('#fuelOrder').value)]));
 document.querySelectorAll('.fuel-quick').forEach(e=>e.onclick=()=>{const input=$('#fuelOrder');input.value=Math.floor(Number(e.dataset.litres)||0);input.dispatchEvent(new Event('input'))});
 $('#fuelOrder')?.addEventListener('input',e=>{const total=Math.max(0,Number(e.target.value)||0)*Number(state.data.business.fuel_buy_price||0);if($('#fuelOrderTotal'))$('#fuelOrderTotal').textContent=money(total)});
 $('[data-act="position"]')?.addEventListener('click',async()=>{const p=await post('getPosition');state.admin.position=p;$('#aCoords').value=`${p.x}, ${p.y}, ${p.z}, ${p.w}`});
 $('#wpRole')?.addEventListener('change',e=>{state.admin.workRole=e.target.value;render()});
 $('[data-act="workPosition"]')?.addEventListener('click',async()=>{const p=await post('getPosition');state.admin.workPosition=p;$('#wpCoords').value=`${p.x}, ${p.y}, ${p.z}, ${p.w}`});
 $('[data-act="addWorkpoint"]')?.addEventListener('click',async()=>{if(!state.admin.workPosition)return toast('Leg eerst de huidige positie vast.',false);const r=await post('adminAddWorkpoint',{businessId:Number($('#wpBusiness').value),role:$('#wpRole').value,label:$('#wpLabel').value,scenario:$('#wpScenario').value,durationMs:Number($('#wpDuration').value)*1000,coords:state.admin.workPosition});if(r.message)toast(r.message,r.success);if(r.success){state.admin.workpoints=r.workpoints||state.admin.workpoints;state.admin.workPosition=null;render()}});
 $('[data-act="adminCreate"]')?.addEventListener('click',async()=>{if(!state.admin.position)return toast('Leg eerst de huidige positie vast.',false);const p=state.admin.position,r=await post('adminCreate',{name:$('#aName').value,type:$('#aType').value,purchasePrice:Number($('#aPrice').value),coords:p,managementCoords:p,deliveryCoords:p,npc:{...p,model:$('#aModel').value},blip:state.admin.defaults.blip});if(r.message)toast(r.message,r.success)});
 document.querySelectorAll('.admin-delete').forEach(e=>e.onclick=async()=>{const r=await post('adminDelete',{id:Number(e.dataset.id)});if(r.message)toast(r.message,r.success);if(r.success){state.admin.businesses=state.admin.businesses.filter(x=>x.id!=e.dataset.id);render()}});
 document.querySelectorAll('.delete-workpoint').forEach(e=>e.onclick=async()=>{const r=await post('adminDeleteWorkpoint',{id:Number(e.dataset.id)});if(r.message)toast(r.message,r.success);if(r.success){state.admin.workpoints=r.workpoints||[];render()}});
}
window.addEventListener('message',e=>{const {action,payload}=e.data||{};if(action==='open'){state.mode='business';state.data=payload;state.tab=payload.business.type==='fuel'?'fuel':'shop';state.cart={};app.classList.remove('hidden');render()}if(action==='refresh'){state.data=payload;render()}if(action==='admin'){state.mode='admin';state.admin=payload;state.tab='creator';app.classList.remove('hidden');render()}if(action==='close')app.classList.add('hidden')});
window.addEventListener('keydown',e=>{if(e.key==='Escape')post('close')});
